version: '3'
services:

  mysql:
    image: 'mysql:5.7'
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 'changeme'

  server:
    depends_on:
      - mysql
    image: 'cbrgm/cmangos:wotlk'
    ports:
      - '8085:8085'
      - '3724:3724'
    restart: always
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_PORT: '3306'
      MYSQL_USER: 'root'
      MYSQL_PWD: 'changeme'
      MYSQL_MANGOS_USER: 'mangos'
      MYSQL_MANGOS_PWD: 'mangos'
      MANGOS_GM_ACCOUNT: 'admin'
      MANGOS_GM_PWD: 'changeme'
      MANGOS_GAMETYPE: 6
      MANGOS_MOTD: 'Welcome!'
      MANGOS_DATABASE_REALM_NAME: 'MyNewServer'
      MANGOS_SERVER_PUBLIC_IP: '116.203.121.99'
      MANGOS_ALLOW_PLAYERBOTS: 0
      MANGOS_ALLOW_AUCTIONBOT_SELLER: 0
      MANGOS_ALLOW_AUCTIONBOT_BUYER: 0
    volumes:
      - ./resources/maps:/opt/mangos/maps
      - ./resources/vmaps:/opt/mangos/vmaps
      - ./resources/mmaps:/opt/mangos/mmaps
      - ./resources/dbc:/opt/mangos/dbc
      - ./resources/cameras:/opt/mangos/Cameras

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    restart: always
    depends_on:
      - mysql
    ports:
      - '8080:80'
    environment:
       PMA_HOST: "mysql"
